
  # Xiaomi Smartmi Air Humidifier 2

- alias: air humidifier target humidity changed
  initial_state: true
  mode: queued
  max: 25
  trigger:
    entity_id: input_number.xiaomi_airpurifier_target_humidity
    platform: state
  action:
    - service: xiaomi_miio.fan_set_target_humidity
      data:
        entity_id: fan.xiaomi_miio_device
        humidity: '{{ states("input_number.xiaomi_airpurifier_target_humidity") | int }}'

- alias: air humidifier led brightness change
  initial_state: true
  mode: queued
  max: 25
  trigger:
    entity_id: input_number.xiaomi_airpurifier_led_brightness
    platform: state
  action:
     - service: xiaomi_miio.fan_set_led_brightness
       data:
         entity_id: fan.xiaomi_miio_device
         brightness: '{{ 2 - states("input_number.xiaomi_airpurifier_led_brightness") | int }}'

- alias: air humidifier 1 target humidity changed
  initial_state: true
  mode: queued
  max: 25
  trigger:
    entity_id: input_number.xiaomi_airpurifier_1_target_humidity
    platform: state
  action:
    - service: xiaomi_miio_airpurifier.fan_set_target_humidity
      data:
        entity_id: fan.xiaomi_miio_device_1
        humidity: '{{ states("input_number.xiaomi_airpurifier_1_target_humidity") | int }}'

- alias: air humidifier 1 led brightness change
  initial_state: true
  mode: queued
  max: 25
  trigger:
    entity_id: input_number.xiaomi_airpurifier_1_led_brightness
    platform: state
  action:
     - service: xiaomi_miio_airpurifier.fan_set_led_brightness
       data:
         entity_id: fan.xiaomi_miio_device_1
         brightness: '{{ states("input_number.xiaomi_airpurifier_1_led_brightness") | int }}'

- alias: air humidifier changed state
  initial_state: true
  mode: restart
  trigger:
    - platform: state
      entity_id: fan.xiaomi_miio_device
      attribute: target_humidity
    - platform: state
      entity_id: fan.xiaomi_miio_device
      attribute: led_brightness
  condition:
    condition: not
    conditions:
      - condition: state
        entity_id: fan.xiaomi_miio_device
        state: 'unavailable'    
  action:
    - service: input_number.set_value
      entity_id: input_number.xiaomi_airpurifier_led_brightness
      data:
        value: '{{ 2 - state_attr("fan.xiaomi_miio_device", "led_brightness") | int }}'
    - service: input_number.set_value
      entity_id: input_number.xiaomi_airpurifier_target_humidity
      data:
        value: >-
                {% if state_attr("fan.xiaomi_miio_device", "target_humidity") | int != 0 -%}
                  {{ state_attr("fan.xiaomi_miio_device", "target_humidity") | int }}
                {%- else -%}
                  40
                {%- endif %}

- alias: air humidifier 1 changed state
  initial_state: true
  mode: restart
  trigger:
    - platform: state
      entity_id: fan.xiaomi_miio_device_1
      attribute: target_humidity
    - platform: state
      entity_id: fan.xiaomi_miio_device_1
      attribute: led_brightness
  condition:
    condition: not
    conditions:
      - condition: state
        entity_id: fan.xiaomi_miio_device_1
        state: 'unavailable'    
  action:
    - service: input_number.set_value
      entity_id: input_number.xiaomi_airpurifier_1_led_brightness
      data:
        value: '{{ state_attr("fan.xiaomi_miio_device_1", "led_brightness") | int }}'
    - service: input_number.set_value
      entity_id: input_number.xiaomi_airpurifier_1_target_humidity
      data:
        value: >-
                {% if state_attr("fan.xiaomi_miio_device_1", "target_humidity") | int != 0 -%}
                  {{ state_attr("fan.xiaomi_miio_device_1", "target_humidity") | int }}
                {%- else -%}
                  40
                {%- endif %}

#Увлажнитель на ночь 1 скорость, днем авто
- alias: air humidifier day and night speed
  initial_state: true
  mode: queued
  max: 25
  trigger:
    - platform: time
      at: "22:00:00"
    - platform: time
      at: "08:00:00"
  condition:
  action:
      - choose:
          - conditions:  
                - condition: state
                  entity_id: fan.xiaomi_miio_device
                  state: 'on'    
            sequence:
                - service: fan.set_speed
                  data:
                    entity_id: fan.xiaomi_miio_device
                    speed: >-
                          {% if '08:00:00' <= as_timestamp(trigger.now) | timestamp_custom('%H:%M:%S')  < '22:00:00' %}
                            Auto
                          {% else %}  
                            Silent 
                          {% endif %}
    #   - choose:
    #       - conditions:  
    #             - condition: state
    #               entity_id: fan.xiaomi_miio_device_1
    #               state: 'on'    
    #         sequence:
    #             - service: fan.set_speed
    #               data:
    #                 entity_id: fan.xiaomi_miio_device_1
    #                 speed: >-
    #                       {% if '08:00:00' <= as_timestamp(trigger.now) | timestamp_custom('%H:%M:%S')  < '22:00:00' %}
    #                         Auto
    #                       {% else %}  
    #                         Low 
    #                       {% endif %}
