
#Обновление сенсоров каждые 2мин
- alias: entity_update_every_2_minutes
  id: entity_update_every_2_minutes
  max_exceeded: silent
  trigger:
    - platform: time_pattern
      minutes: "/2"
    - platform: homeassistant
      event: start
  action:
    - action: homeassistant.update_entity
      data: 
        entity_id:
          - binary_sensor.internet_availability_nic_ping
          - binary_sensor.internet_availability_yandex_ping
