
#Обновление сенсоров каждые 2мин
- alias: entity_update_every_2_minutes
  id: entity_update_every_2_minutes
  max_exceeded: silent
  triggers:
    - trigger: time_pattern
      minutes: "/2"
    - trigger: homeassistant
      event: start
  actions:
    - action: homeassistant.update_entity
      data: 
        entity_id:
          - binary_sensor.internet_availability_nic_ping
          - binary_sensor.internet_availability_yandex_ping
