
homeassistant:
  name: Kotletochka home
  latitude: !secret latitude_coord
  longitude: !secret longitude_coord
  elevation: 161
  unit_system: metric
  time_zone: Europe/Moscow
  customize: !include_dir_merge_named includes/customize
  allowlist_external_dirs:
   - /config
  external_url: !secret external_url_enzokot
  internal_url: "http://kotletochkarpi4:8123/"
  auth_mfa_modules:
   - type: totp
   - type: notify
     message: "\U0001F511 *Двухфакторная аутентификация*\n`{}` код для завершения авторизации Home Assistant"

config:
frontend:
lovelace:
  mode: yaml
  resources: !include includes/resources.yaml
panel_custom: !include includes/panel_custom.yaml
panel_iframe: !include includes/panel_iframe.yaml

dhcp:
ssdp:
system_health:
mobile_app:
zeroconf:

http:
  login_attempts_threshold: 5
  ip_ban_enabled: true
  use_x_forwarded_for: true
  trusted_proxies: 
    - 127.0.0.1
    - ::1
    - 172.30.33.0/24

hacs:
  token: !secret HACS_github

mqtt:
  broker: core-mosquitto
  username: mqtt
  password: !secret mqtt_broker_password
  birth_message:
    topic: 'homeassistant/status'
    payload: 'online'
    retain: true
  will_message:
    topic: 'homeassistant/status'
    payload: 'offline'
    retain: true

history:
logbook:
recorder: !include includes/recorder.yaml
logger:
  default: info

group: !include includes/groups.yaml
automation: !include_dir_merge_list includes/automation
script: !include_dir_merge_named includes/scripts
scene: !include includes/scenes.yaml
zone: !include includes/zone.yaml

notify: !include includes/notify.yaml
telegram_bot: !include includes/telegram_bot.yaml

yeelight: !include includes/yeelight.yaml
fan: !include includes/fan.yaml
camera: !include includes/camera.yaml

switch: !include_dir_merge_list includes/switches
sensor: !include_dir_merge_list includes/sensor
binary_sensor: !include_dir_merge_list includes/binary_sensor
timer: !include includes/timer.yaml
utility_meter: !include includes/utility_meter.yaml

input_select: !include includes/input_select.yaml
input_number: !include includes/input_number.yaml
input_text: !include includes/input_text.yaml
input_boolean: !include includes/input_boolean.yaml
input_datetime: !include includes/input_datetime.yaml

webostv: !include includes/webostv.yaml
media_player: !include includes/media_player.yaml
smartir: 
climate: !include includes/smartir/climate.yaml
start_time:

#device_tracker: !include includes/device_tracker.yaml
