
homeassistant:
  name: Kotletochka home
  latitude: !secret latitude_coord
  longitude: !secret longitude_coord
  elevation: 161
  unit_system: metric
  time_zone: Europe/Moscow
  currency: RUB
  customize: !include_dir_merge_named includes/customize
  allowlist_external_dirs:
    - /config
  external_url: !secret external_url
  internal_url: "http://kotletochka-dell-srv.local:8123/"
  auth_mfa_modules:
    - type: totp
    - type: notify
      message: "\U0001F511 *Двухфакторная аутентификация*\n`{}` код для завершения авторизации Home Assistant"

config:
frontend:
lovelace:
  mode: yaml
  resources: !include includes/resources.yaml
panel_custom: !include includes/panel_custom.yaml
panel_iframe: !include includes/panel_iframe.yaml

dhcp:
ssdp:
system_health:
mobile_app:
zeroconf:
network:
discovery:

http:
  login_attempts_threshold: 5
  ip_ban_enabled: true
  use_x_forwarded_for: true
  trusted_proxies: 
    - 127.0.0.1
    - ::1
    - 172.30.33.0/24
    - 192.168.217.1

#websocket_api:

history:
logbook:
recorder: !include includes/recorder.yaml
influxdb: !include includes/influxdb.yaml
logger:
  default: warn
  filters:
    homeassistant.components.xiaomi_miio:
      - "Timeout fetching Увлажнитель детская data"
      - "Timeout fetching Увлажнитель спальня data"
      - "Timeout fetching Xiaomi Vacuum cleaner data"
system_log:
  fire_event: true

group: !include includes/groups.yaml
automation: !include_dir_merge_list includes/automation
script: !include_dir_merge_named includes/scripts
scene: !include includes/scenes.yaml
zone: !include includes/zone.yaml

notify: !include includes/notify.yaml
telegram_bot: !include includes/telegram_bot.yaml
alert: !include includes/alert.yaml

camera: !include includes/camera.yaml

switch: !include_dir_merge_list includes/switches
sensor: !include_dir_merge_list includes/sensor
binary_sensor: !include_dir_merge_list includes/binary_sensor
template: !include_dir_merge_list includes/template_sensors
timer: !include includes/timer.yaml
energy:
utility_meter: !include includes/utility_meter.yaml
rest_command: !include includes/rest_command.yaml
shell_command: !include includes/shell_command.yaml
cover: !include includes/cover.yaml

input_select: !include includes/input_select.yaml
input_number: !include includes/input_number.yaml
input_text: !include includes/input_text.yaml
input_boolean: !include includes/input_boolean.yaml
input_datetime: !include includes/input_datetime.yaml
counter: !include includes/counters.yaml

python_script:
yandex_smart_home: !include includes/yandex_smart_home.yaml
yandex_station: !include includes/yandex_station.yaml
xiaomi_gateway3: !include includes/xiaomi_gateway3.yaml

conversation: !include includes/conversation.yaml
media_player: !include includes/media_player.yaml
smartir: 
climate: !include includes/smartir/climate.yaml
feedreader: !include includes/feedreader.yaml
