substitutions:
  devicename: avatto-s06-living-room
  telegram_api_token: !secret telegram_api
  telegram_chat_id: !secret telegram_enzokot_chat_id  

esphome:
  name: $devicename
  platform: ESP8266
  board: esp_wroom_02
  #board: esp01_1m
  comment: IR and notify telegram HA state living room

wifi:
  fast_connect: true
  networks:
  #Точка в спальне
#  - ssid: Kotletochka
#    password: !secret wifi_password
#    bssid: "50:ff:20:4b:10:73"
#    priority: 1

  #Точка на кухне
#  - ssid: Kotletochka
#    password: !secret wifi_password
#    bssid: "50:ff:20:4a:bf:cd"
#    priority: 1

  #Основная точка
  - ssid: Kotletochka
    password: !secret wifi_password
    bssid: "50:ff:20:3c:2b:74"
    priority: 2
  
#  - ssid: Kotletochka_Yi
#    password: !secret wifi_password
#    hidden: true
#    priority: 1
    
#  - ssid: Kotletochka_kit
#    password: !secret wifi_password
#    hidden: true
#    priority: 1

  ap:
    ssid: "${devicename}"
    password: !secret wifi_password

captive_portal:

http_request:

logger:
  baud_rate: 0

syslog:
  ip_address: "kotletochka-ds.local"
    
api:
  reboot_timeout: 0s
  services:
    - service: send_samsung_command
      variables:
        data: string
      then:
        - remote_transmitter.transmit_samsung:
            data: !lambda 'return strtoul(data.c_str(), nullptr, 16);'
    - service: send_lg_command
      variables:
        data: string
        nbits: int
      then:
        - remote_transmitter.transmit_lg:
            data: !lambda 'return strtoul(data.c_str(), nullptr, 16);'
            nbits: !lambda 'return nbits;'
    - service: send_raw_command
      variables:
        data: int[]
      then:
        - remote_transmitter.transmit_raw:
            code: !lambda 'return data;'

ota:
  password: !secret ota_password

time:
  - platform: sntp
    id: sntp_time
    servers: 'kotletochka.local'
    timezone: 'Europe/Moscow'

status_led:
  pin: GPIO4

remote_receiver:
  pin: 
    number: GPIO5
    mode: INPUT_PULLUP
    inverted: true
  dump: all
  tolerance: 55
  id: "receiver_s06_living_room"

remote_transmitter:
  pin: 
    number: GPIO14
    inverted: false
  carrier_duty_percent: 50%
  id: "transmitter_s06_living_room"

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO13
      inverted: true
    internal: true
    name: "${devicename}_Button"
    id: "button_s06_living_room"

  - platform: status
    name: "$devicename Status"
    id: status_connection
    internal: true
    on_state:
          then:
            - if:
                condition:
                    - binary_sensor.is_on: "status_connection"
                    - lambda: 'return id(uptime_sec).state > 60;'
                then:
                  - http_request.post:
                      url: "https://api.telegram.org/bot${telegram_api_token}/sendMessage"
                      verify_ssl: false
                      headers:
                        Content-Type: application/json
                      json:
                        chat_id: "${telegram_chat_id}"
                        parse_mode: "HTML"
                        text: "\U00002705 <b>Трекинг устройств</b>\n${devicename}: Home Assistant доступен"

            - if:
                condition:
                    - binary_sensor.is_off: "status_connection"
                    - lambda: 'return id(uptime_sec).state > 60;'
                then:
                  - http_request.post:
                      url: "https://api.telegram.org/bot${telegram_api_token}/sendMessage"
                      verify_ssl: false
                      headers:
                        Content-Type: application/json
                      json:
                        chat_id: "${telegram_chat_id}"
                        parse_mode: "HTML"
                        text: "\U000026d4 <b>Трекинг устройств</b>\n${devicename}: Home Assistant <b>недоступен</b>"
    
climate:
  - platform: fujitsu_general
    name: "Avatto living room AC"
    sensor: temp_for_avatto_ac_living_room
    visual:
          min_temperature: 18 °C    
    receiver_id: receiver_s06_living_room
    
sensor:
  - platform: homeassistant
    name: "Temperature living room"
    internal: true
    device_class: temperature
    accuracy_decimals: 1
    entity_id: sensor.esp_xiaomi_living_room_temperature
    id: temp_for_avatto_ac_living_room

  - platform: uptime
    name: "$devicename Uptime Sensor"
    id: uptime_sec
    update_interval: 15s

  - platform: wifi_signal
    name: "$devicename WiFi RSSI"
    update_interval: 60s

text_sensor:
  - platform: wifi_info
    ssid:
      name: "${devicename} Connected SSID"
    bssid:
      name: "${devicename} Connected BSSID" 

button:
  - platform: restart
    name: ${devicename}_Restart

  - platform: safe_mode
    name: ${devicename}_Safe_Mode
