substitutions:
  devicename: ble_tracker_bed_room
  nodename: ble-tracker-bed-room

external_components:
  - source: github://TheStaticTurtle/esphome_syslog
    components: [syslog]

esphome:
  name: $nodename
  comment: BLE bed room

esp32:
  board: wemos_d1_mini32

#external_components:
#  - source: github://myhomeiot/esphome-components

wifi:
  fast_connect: true
  output_power: 20.5dB
  networks:
  #Точка в спальне
  - ssid: Kotletochka
    password: !secret wifi_password
    bssid: "50:ff:20:4b:10:73"
    priority: 2
  
  #Основная точка
#  - ssid: Kotletochka
#    password: !secret wifi_password
#    bssid: "50:ff:20:3c:2b:74"
#    priority: 1

  #Точка на кухне
#  - ssid: Kotletochka
#    password: !secret wifi_password
#    bssid: "50:ff:20:4a:bf:cd"
#    priority: 1

#  - ssid: Kotletochka_Yi
#    password: !secret wifi_password
#    hidden: true
#    priority: 0
  
#  - ssid: Kotletochka_kit
#    password: !secret wifi_password
#    hidden: true
#    priority: 0

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${nodename}"
    password: !secret wifi_password

captive_portal:

# Enable logging
logger:
  #level: NONE
  #baud_rate: 0

syslog:
  ip_address: "kotletochka-ds.local"

# Enable Home Assistant API
api:
  reboot_timeout: 0s

ota:
  password: !secret ota_password

# Веб сервер
#web_server:
#  port: 80

time:
  - platform: sntp
    id: sntp_time
    servers: 'kotletochka.local'
    timezone: 'Europe/Moscow'

esp32_ble_tracker:
 scan_parameters:
    #interval: 320ms
    #window: 30ms
    active: false
    #interval: 512ms
    #window: 48ms

#ble_gateway:
#  on_ble_advertise:
#    then:
#      - homeassistant.event:
#          event: esphome.on_ble_advertise
#          data:
#            packet: !lambda return packet;
#            gateway_id: ${devicename}

sensor:
  - platform: xiaomi_lywsd02
    mac_address: !secret clock_bt_bed_room_mac
    temperature:
      name: "ESP Xiaomi Bed Room Temperature"
    humidity:
      name: "ESP Xiaomi Bed Room Humidity"
    battery_level:
      name: "ESP Xiaomi Bed Room Battery Level"

  - platform: wifi_signal
    name: "${devicename}_WiFi_RSSI"
    update_interval: 60s

switch:
  - platform: gpio
    id: onboard_led
    name: "${devicename}_On_Board_Led"
    pin:
      number: GPIO2
      mode: OUTPUT
    restore_mode: ALWAYS_OFF

text_sensor:
  - platform: wifi_info
    ssid:
      name: "${devicename}_Connected_SSID"
    bssid:
      name: "${devicename}_Connected_BSSID" 

binary_sensor:
  - platform: status
    name: "${devicename}_Status"
    id: status_connection
    internal: true
    on_state:
          then:
            - if:
                condition:
                    - binary_sensor.is_on: "status_connection"
                then:
                  - switch.turn_on: "onboard_led"
                  
            - if:
                condition:
                    - binary_sensor.is_off: "status_connection"
                then:
                  - switch.turn_off: "onboard_led"

button:
  - platform: restart
    name: ${devicename}_Restart

  - platform: safe_mode
    name: ${devicename}_Safe_Mode
