substitutions:
  devicename: ble_tracker_childrens_room
  nodename: ble-tracker-childrens-room
  time_service_uuid: ebe0ccb0-7a0a-4b0c-8a1a-6ff2997da3a6
  time_characteristic_uuid: EBE0CCB7-7A0A-4B0C-8A1A-6FF2997DA3A6

esphome:
  name: $nodename
  comment: Monitoring HA state and BLE childrens room

esp32:
  board: wemos_d1_mini32

wifi:
  fast_connect: true
  networks:
  
#  - ssid: Kotletochka_Yi
#    password: !secret wifi_password
#    hidden: true
#    priority: 1
  
#  - ssid: Kotletochka_kit
#    password: !secret wifi_password
#    hidden: true
#    priority: 1
  
  #Точка в спальне
#  - ssid: Kotletochka
#    password: !secret wifi_password
#    bssid: "50:ff:20:c5:72:2d"
#    priority: 1

  #Точка на кухне
#  - ssid: Kotletochka
#    password: !secret wifi_password
#    bssid: "50:ff:20:c5:8a:b1"
#    priority: 1

  #Основная точка
  - ssid: Kotletochka
    password: !secret wifi_password
    bssid: "50:ff:20:9e:1d:1e"
    priority: 2
    
  ap:
    ssid: "${nodename}"
    password: !secret wifi_password

captive_portal:

udp:
  id: kotletochka_ds_udp
  addresses: !secret kotletochka-ds-lan-ip

# Enable logging
logger:
  #level: NONE
  #baud_rate: 0

syslog:
  udp_id: kotletochka_ds_udp
  time_id: sntp_time
  level: 'INFO'
    
# Enable Home Assistant API
api:
  reboot_timeout: 0s

ota:
  - platform: esphome
    password: !secret ota_password

time:
  - platform: sntp
    id: sntp_time
    servers: 
      - 192.168.217.30
      - ntp2.vniiftri.ru
      - pool.ntp.org
    timezone: Europe/Moscow
    on_time:
      - seconds: 0
        minutes: 0
        hours: 11
        days_of_month: 1-7
        days_of_week: SAT
        then:
          - logger.log: "Starting room clock synchronization"          
          - if:
              condition:
                not:
                  - script.is_running: time_sync_ble_clocks
              then:
                - script.execute: time_sync_ble_clocks

text_sensor:
  - platform: wifi_info
    ssid:
      name: "${devicename}_Connected_SSID"
    bssid:
      name: "${devicename}_Connected_BSSID" 

esp32_ble_tracker:
  scan_parameters:
    #window: 48ms
    #interval: 512ms
    active: false

ble_client:
  - mac_address: !secret clock_bt_childrens_room_mac
    id: lywsd02_clock_childrens_room
    auto_connect: false
    on_connect:
      then:
        - lambda: |-
            ESP_LOGD("ble_client_lambda", "Connected to lywsd02_clock_childrens_room!");
    on_disconnect:
      then:
        - lambda: |-
            ESP_LOGD("ble_client_lambda", "Disconnected from lywsd02_clock_childrens_room!");

script:
  - id: time_sync_ble_clocks
    mode: queued
    then:
      - esp32_ble_tracker.stop_scan:
      - ble_client.connect: lywsd02_clock_childrens_room
      - lambda: |-
          id(sntp_time).update();
      - delay: 10s
      - ble_client.ble_write:
          id: lywsd02_clock_childrens_room
          service_uuid: ${time_service_uuid}
          characteristic_uuid: ${time_characteristic_uuid}
          value: !lambda |-
              auto time = id(sntp_time).now();
              auto timezone = time.timezone_offset() / 3600;
              if (timezone < 0) {
                timezone += 256;
              }
              uint8_t time_byte1 =  time.timestamp & 0x000000ff;
              uint8_t time_byte2 = (time.timestamp & 0x0000ff00) >> 8;
              uint8_t time_byte3 = (time.timestamp & 0x00ff0000) >> 16;
              uint8_t time_byte4 = (time.timestamp & 0xff000000) >> 24;
              uint8_t timezone_byte = timezone;
              return {time_byte1, time_byte2, time_byte3, time_byte4, timezone_byte};
      - delay: 5s
      - ble_client.disconnect: lywsd02_clock_childrens_room
      - esp32_ble_tracker.start_scan:

sensor:
  - platform: xiaomi_lywsd02
    mac_address: !secret clock_bt_childrens_room_mac
    temperature:
      name: "ESP Xiaomi Childrens Room Temperature"
      filters:
          - timeout: 1h
    humidity:
      name: "ESP Xiaomi Childrens Room Humidity"
      filters:
          - timeout: 1h
    battery_level:
      name: "ESP Xiaomi Childrens Room Battery Level"
  
  - platform: uptime
    name: "${devicename}_Uptime_Sensor"
    id: uptime_sec
    update_interval: 15s

  - platform: wifi_signal
    name: "${devicename}_WiFi_RSSI"
    update_interval: 60s

button:
  - platform: restart
    name: ${devicename}_Restart
    id: button_restart

  - platform: safe_mode
    name: ${devicename}_Safe_Mode
    id: button_restart_safe_mode
