substitutions:
  devicename: ble_tracker_childrens_room
  nodename: ble-tracker-childrens-room

external_components:
  - source: github://TheStaticTurtle/esphome_syslog
    components: [syslog]

esphome:
  name: $nodename
  comment: BLE childrens room

esp32:
  board: wemos_d1_mini32

wifi:
  fast_connect: true
  networks:
  
#  - ssid: Kotletochka_Yi
#    password: !secret wifi_password
#    hidden: true
#    priority: 1
  
#  - ssid: Kotletochka_kit
#    password: !secret wifi_password
#    hidden: true
#    priority: 1
  
  #Точка в спальне
#  - ssid: Kotletochka
#    password: !secret wifi_password
#    bssid: "50:ff:20:4b:10:73"
#    priority: 1

  #Точка на кухне
#  - ssid: Kotletochka
#    password: !secret wifi_password
#    bssid: "50:ff:20:4a:bf:cd"
#    priority: 1

  #Основная точка
  - ssid: Kotletochka
    password: !secret wifi_password
    bssid: "50:ff:20:3c:2b:74"
    priority: 2
    
  ap:
    ssid: "${nodename}"
    password: !secret wifi_password

captive_portal:

# Enable logging
logger:
  #level: NONE
  #baud_rate: 0

syslog:
  ip_address: "kotletochka-ds.local"
    
# Enable Home Assistant API
api:
  reboot_timeout: 0s

ota:
  password: !secret ota_password

time:
  - platform: sntp
    id: sntp_time
    servers: 'kotletochka.local'
    timezone: 'Europe/Moscow'

text_sensor:
  - platform: wifi_info
    ssid:
      name: "${devicename}_Connected_SSID"
    bssid:
      name: "${devicename}_Connected_BSSID" 

esp32_ble_tracker:
  scan_parameters:
    #window: 48ms
    #interval: 512ms
    active: false

sensor:
  - platform: xiaomi_lywsd02
    mac_address: !secret clock_bt_childrens_room_mac
    temperature:
      name: "ESP Xiaomi Childrens Room Temperature"
      filters:
          - timeout: 1h
    humidity:
      name: "ESP Xiaomi Childrens Room Humidity"
      filters:
          - timeout: 1h
    battery_level:
      name: "ESP Xiaomi Childrens Room Battery Level"
  
  - platform: uptime
    name: "${devicename}_Uptime_Sensor"
    id: uptime_sec
    update_interval: 15s

  - platform: wifi_signal
    name: "${devicename}_WiFi_RSSI"
    update_interval: 60s

button:
  - platform: restart
    name: ${devicename}_Restart

  - platform: safe_mode
    name: ${devicename}_Safe_Mode
