substitutions:
  devicename: ble_tracker_livingroom
  nodename: ble-tracker-livingroom
  time_service_uuid: ebe0ccb0-7a0a-4b0c-8a1a-6ff2997da3a6
  time_characteristic_uuid: EBE0CCB7-7A0A-4B0C-8A1A-6FF2997DA3A6

esphome:
  name: $nodename
  comment: Monitoring HA state and BLE living room
  on_boot:
    priority: -10
    then:
      - lambda: 'id(weight_miscale).update();'

esp32:
  board: wemos_d1_mini32

wifi:
  #fast_connect: true
  networks:
  
#  - ssid: Kotletochka_Yi
#    password: !secret wifi_password
#    hidden: true
#    priority: 1
  
#  - ssid: Kotletochka_kit
#    password: !secret wifi_password
#    hidden: true
#    priority: 1
  
  #Точка в спальне
#  - ssid: Kotletochka
#    password: !secret wifi_password
#    bssid: "50:ff:20:c5:72:2d"
#    priority: 1

  #Точка на кухне
  - ssid: Kotletochka
    password: !secret wifi_password
    bssid: "50:ff:20:c5:8a:b1"
    priority: 3

  #Основная точка
  - ssid: Kotletochka
    password: !secret wifi_password
    bssid: "50:ff:20:9e:1d:1e"
    priority: 2
    
  ap:
    ssid: "${nodename}"
    password: !secret wifi_password

captive_portal:

udp:
  id: kotletochka_ds_udp
  addresses: !secret kotletochka-ds-lan-ip

# Enable logging
logger:
  #level: NONE
  #baud_rate: 0

syslog:
  udp_id: kotletochka_ds_udp
  time_id: sntp_time
  level: 'INFO'
    
# Enable Home Assistant API
api:  
  reboot_timeout: 0s

ota:
  - platform: esphome
    password: !secret ota_password

time:
  - platform: sntp
    id: sntp_time
    servers: 
      - 192.168.217.1
      - ntp2.vniiftri.ru
      - pool.ntp.org
    timezone: Europe/Moscow
    on_time:      
      - seconds: 0
        minutes: 0
        hours: 11
        days_of_month: 1-7
        days_of_week: SAT
        then:
          - logger.log: "Starting room clock synchronization"
          - if:
              condition:
                not:
                  - script.is_running: time_sync_ble_clocks
              then:
                - script.execute: time_sync_ble_clocks

globals:
   - id: weight_global_float
     type: float
     restore_value: yes
     initial_value: '0.0'

switch:
  - platform: gpio
    id: onboard_led
    name: "${devicename}_On_Board_Led"
    pin:
      number: GPIO2
      mode: OUTPUT
    restore_mode: ALWAYS_OFF    

text_sensor:
  - platform: wifi_info
    ssid:
      name: "${devicename}_Connected_SSID"
    bssid:
      name: "${devicename}_Connected_BSSID" 

binary_sensor:
  - platform: status
    name: "${devicename}_Status"
    id: status_connection
    internal: true
    on_state:
          then:
            - if:
                condition:
                  - binary_sensor.is_on: "status_connection"
                then:
                  - switch.turn_on: "onboard_led"

            - if:
                condition:
                  - binary_sensor.is_off: "status_connection"
                then:
                  - switch.turn_off: "onboard_led"

esp32_ble_tracker:
  scan_parameters:
    #window: 48ms
    #interval: 512ms
    active: false

ble_client:
  - mac_address: !secret clock_bt_living_room_mac
    id: lywsd02_clock_living_room
    auto_connect: false
    on_connect:
      then:
        - lambda: |-
            ESP_LOGD("ble_client_lambda", "Connected to lywsd02_clock_living_room!");
    on_disconnect:
      then:
        - lambda: |-
            ESP_LOGD("ble_client_lambda", "Disconnected from lywsd02_clock_living_room!");

  - mac_address: !secret clock_bt_kitchen_mac
    id: lywsd02_clock_kitchen
    auto_connect: false
    on_connect:
      then:
        - lambda: |-
            ESP_LOGD("ble_client_lambda", "Connected to lywsd02_clock_kitchen!");
    on_disconnect:
      then:
        - lambda: |-
            ESP_LOGD("ble_client_lambda", "Disconnected from lywsd02_clock_kitchen!");

script:
  - id: time_sync_ble_clocks
    mode: queued
    then:
      - esp32_ble_tracker.stop_scan:
      - ble_client.connect: lywsd02_clock_living_room
      - lambda: |-
          id(sntp_time).update();
      - delay: 10s
      - ble_client.ble_write:
          id: lywsd02_clock_living_room
          service_uuid: ${time_service_uuid}
          characteristic_uuid: ${time_characteristic_uuid}
          value: !lambda |-
              auto time = id(sntp_time).now();
              auto timezone = time.timezone_offset() / 3600;
              if (timezone < 0) {
                timezone += 256;
              }
              uint8_t time_byte1 =  time.timestamp & 0x000000ff;
              uint8_t time_byte2 = (time.timestamp & 0x0000ff00) >> 8;
              uint8_t time_byte3 = (time.timestamp & 0x00ff0000) >> 16;
              uint8_t time_byte4 = (time.timestamp & 0xff000000) >> 24;
              uint8_t timezone_byte = timezone;
              return {time_byte1, time_byte2, time_byte3, time_byte4, timezone_byte};
      - delay: 5s
      - ble_client.disconnect: lywsd02_clock_living_room

      - ble_client.connect: lywsd02_clock_kitchen
      - ble_client.ble_write:
          id: lywsd02_clock_kitchen
          service_uuid: ${time_service_uuid}
          characteristic_uuid: ${time_characteristic_uuid}
          value: !lambda |-
              auto time = id(sntp_time).now();
              auto timezone = time.timezone_offset() / 3600;
              if (timezone < 0) {
                timezone += 256;
              }
              uint8_t time_byte1 =  time.timestamp & 0x000000ff;
              uint8_t time_byte2 = (time.timestamp & 0x0000ff00) >> 8;
              uint8_t time_byte3 = (time.timestamp & 0x00ff0000) >> 16;
              uint8_t time_byte4 = (time.timestamp & 0xff000000) >> 24;
              uint8_t timezone_byte = timezone;
              return {time_byte1, time_byte2, time_byte3, time_byte4, timezone_byte};
      - delay: 5s
      - ble_client.disconnect: lywsd02_clock_kitchen          
      - esp32_ble_tracker.start_scan:          

sensor:
  - platform: uptime
    name: "${devicename}_Uptime_Sensor"
    id: uptime_sec
    update_interval: 15s

  - platform: wifi_signal
    name: "${devicename}_WiFi_RSSI"
    update_interval: 60s
    
  - platform: xiaomi_lywsd02
    mac_address: !secret clock_bt_living_room_mac
    temperature:
      name: "ESP Xiaomi Living Room Temperature"
      filters:
          - timeout: 1h
    humidity:
      name: "ESP Xiaomi Living Room Humidity"
      filters:
          - timeout: 1h
    battery_level:
      name: "ESP Xiaomi Living Room Battery Level"

  - platform: xiaomi_lywsd02
    mac_address: !secret clock_bt_kitchen_mac
    temperature:
      name: "ESP Xiaomi Kitchen Temperature"
      filters:
          - timeout: 1h
    humidity:
      name: "ESP Xiaomi Kitchen Humidity"
      filters:
          - timeout: 1h
    battery_level:
      name: "ESP Xiaomi Kitchen Battery Level"

  - platform: xiaomi_miscale
    mac_address: !secret xiaomi_mi_scale_mac
    weight:
      id: weight_miscale_ble
      internal: true
      force_update: true
      on_value:
        then:
          - lambda: |-
              {id(weight_global_float) = x;}
          - lambda: 'id(weight_miscale).update();'

  - platform: template
    name: "ESP Xiaomi Mi Scale Weight"
    id: weight_miscale
    unit_of_measurement: 'kg'
    icon: mdi:weight-kilogram
    accuracy_decimals: 2
    update_interval: never
    force_update: true
    lambda: |-
      {return id(weight_global_float);}

button:
  - platform: restart
    name: ${devicename}_Restart
    id: button_restart

  - platform: safe_mode
    name: ${devicename}_Safe_Mode
    id: button_restart_safe_mode
