substitutions:
  devicename: digma-sc001-kitchen
  telegram_api_token: !secret telegram_api
  telegram_chat_id: !secret telegram_enzokot_chat_id  

esphome:
  name: $devicename
  platform: ESP8266
  board: esp01_1m
  comment: Digma IR for kitchen

wifi:
  fast_connect: true
  networks:

  #Точка на кухне
  - ssid: Kotletochka
    password: !secret kotletochka_wifi_password
    bssid: "50:ff:20:4a:bf:cd"
    priority: 1

  #Основная точка
#  - ssid: Kotletochka
#    password: !secret kotletochka_wifi_password
#    bssid: "50:ff:20:3c:2b:74"
#    priority: 2
  
  ap:
    ssid: "${devicename}"
    password: !secret kotletochka_wifi_password

captive_portal:

logger:

api:
  password: !secret api_password
  reboot_timeout: 0s
  services:
    - service: send_samsung_command
      variables:
        data: string
      then:
        - remote_transmitter.transmit_samsung:
            data: !lambda 'return strtoul(data.c_str(), nullptr, 16);'
    - service: send_lg_command
      variables:
        data: string
        nbits: int
      then:
        - remote_transmitter.transmit_lg:
            data: !lambda 'return strtoul(data.c_str(), nullptr, 16);'
            nbits: !lambda 'return nbits;'
    - service: send_raw_command
      variables:
        data: int[]
      then:
        - remote_transmitter.transmit_raw:
            code: !lambda 'return data;'

ota:
  password: !secret ota_password

status_led:
  pin: 
    number: GPIO4
    inverted: true

remote_receiver:
  pin: 
    number: GPIO5
    inverted: true
  dump: all
  id: "receiver_sc001_kitchen"

remote_transmitter:
  pin: 
    number: GPIO14
    inverted: false
  carrier_duty_percent: 50%
  id: "transmitter_sc001_kitchen"

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO13
      inverted: true
    internal: true
    name: "${devicename}_Button"
    id: button

sensor:
  - platform: uptime
    name: "$devicename Uptime Sensor"
    id: uptime_sec
    update_interval: 15s    

  - platform: wifi_signal
    name: "$devicename WiFi RSSI"
    update_interval: 60s

switch:
  - platform: restart
    name: "$devicename Restart"

text_sensor:
  - platform: wifi_info
    ssid:
      name: "${devicename} Connected SSID"
    bssid:
      name: "${devicename} Connected BSSID" 
