substitutions:
  devicename: perenio_petra01_kitchen
  nodename: perenio-petra01-kitchen
  telegram_api_token: !secret telegram_api
  telegram_chat_id: !secret telegram_enzokot_chat_id  

esphome:
  name: $nodename
  comment: IR and notify telegram HA state kitchen

esp8266:
  board: esp_wroom_02

wifi:
  fast_connect: true
  networks:

  #Точка на кухне
  - ssid: Kotletochka
    password: !secret wifi_password
    bssid: "50:ff:20:c5:8a:b1"
    priority: 2

  ap:
    ssid: "${nodename}"
    password: !secret wifi_password

captive_portal:

http_request:
  verify_ssl: false

udp:
  id: kotletochka_ds_udp
  addresses: !secret kotletochka-ds-lan-ip

logger:
  #baud_rate: 0

syslog:
  udp_id: kotletochka_ds_udp
  time_id: sntp_time
  level: 'INFO'
    
api:
  reboot_timeout: 0s
  services:
    - service: send_samsung_command
      variables:
        data: string
      then:
        - remote_transmitter.transmit_samsung:
            data: !lambda 'return strtoul(data.c_str(), nullptr, 16);'
    - service: send_lg_command
      variables:
        data: string
        nbits: int
      then:
        - remote_transmitter.transmit_lg:
            data: !lambda 'return strtoul(data.c_str(), nullptr, 16);'
            nbits: !lambda 'return nbits;'
    - service: send_raw_command
      variables:
        data: int[]
      then:
        - remote_transmitter.transmit_raw:
            code: !lambda 'return data;'

ota:
  - platform: esphome
    password: !secret ota_password

time:
  - platform: sntp
    id: sntp_time
    servers: 
      - 192.168.217.30
      - ntp2.vniiftri.ru
      - pool.ntp.org
    timezone: Europe/Moscow

status_led:
  pin: GPIO4

remote_receiver:
  pin: 
    number: GPIO5
    mode: INPUT_PULLUP
    inverted: true
  dump: all
  tolerance: 55%
  id: receiver_petra01_kitchen

remote_transmitter:
  pin: 
    number: GPIO14
    inverted: false
  carrier_duty_percent: 50%
  id: transmitter_petra01_kitchen

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO13
      inverted: true
    internal: true
    name: "${devicename}_Button"
    id: button_petra01_kitchen
    on_double_click:
      then:
        - button.press: button_restart_safe_mode

  - platform: status
    name: "${devicename}_Status"
    id: status_connection
    internal: true
    on_state:
          then:
            - if:
                condition:
                    - binary_sensor.is_on: "status_connection"
                    - lambda: 'return id(uptime_sec).state > 60;'
                then:
                  - http_request.post:
                      url: "https://api.telegram.org/bot${telegram_api_token}/sendMessage"                      
                      request_headers:
                        Content-Type: application/json
                      json:
                        chat_id: "${telegram_chat_id}"
                        parse_mode: "HTML"
                        text: "\U00002705 <b>Трекинг устройств</b>\n${nodename}: Home Assistant доступен"

            - if:
                condition:
                    - binary_sensor.is_off: "status_connection"
                    - lambda: 'return id(uptime_sec).state > 60;'
                then:
                  - http_request.post:
                      url: "https://api.telegram.org/bot${telegram_api_token}/sendMessage"
                      request_headers:
                        Content-Type: application/json
                      json:
                        chat_id: "${telegram_chat_id}"
                        parse_mode: "HTML"
                        text: "\U000026d4 <b>Трекинг устройств</b>\n${nodename}: Home Assistant <b>недоступен</b>"
    
sensor:
  - platform: uptime
    name: "${devicename}_Uptime Sensor"
    id: uptime_sec
    update_interval: 15s

  - platform: wifi_signal
    name: "${devicename}_WiFi_RSSI"
    update_interval: 60s

text_sensor:
  - platform: wifi_info
    ssid:
      name: "${devicename}_Connected_SSID"
    bssid:
      name: "${devicename}_Connected_BSSID" 

button:
  - platform: restart
    name: ${devicename}_Restart
    id: button_restart

  - platform: safe_mode
    name: ${devicename}_Safe_Mode
    id: button_restart_safe_mode
